#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ec="emacsclient -n"
alias dc="docker-compose"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias kubep="kubectl --kubeconfig='$HOME/.kube/config.prod'"

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='emacsclient -n'
fi

export GIT_EDITOR "emacsclient"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

export GOPATH="$HOME/Development/go"
export PATH="$GOPATH/bin:$PATH"

export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="./bin:$PATH"

export NVM_DIR="$HOME/.dotfiles/nvm"
source "$HOME/.dotfiles/nvm/nvm.sh"

export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH="$HOME/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src"

docker-rmi-untagged() {
    docker rmi $(docker images | grep "^<none>" | awk '{ print $3 }')
}

docker-rm-stopped() {
    docker rm $(docker ps -a -q)
}

clone-ivx() {
    git clone git@github.com:ivx/"$1".git
}

# load local config if available
[[ -f ~/.local-env ]] && source ~/.local-env

# hook direnv
eval "$(direnv hook zsh)"
